name: root
dependencies:
  - python=3.4
  - pymongo=2.8
  - nose
  - flask
  - requests
  - cssselect
  - docopt
  - boto3
  - node
  - gunicorn
  - bokeh
  - pip:
    - mongoengine==0.8.7
    - flask-mongoengine==0.7.1
    - flask-testing
    - pandas
    - click
    - flask-api
    - flask-stormpath
    - hurry.filesize
    - uwsgi
    - flask-restful-swagger
    - simplejson
    - bokeh
